//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeDataHub.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradeDataHub.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Data Hub v2.0
        ///
        ///A comprehensive solution for importing and exporting trade data with advanced filtering and monitoring capabilities.
        ///
        ///Features:
        ///• Excel file generation for trade data
        ///• Advanced parameter filtering
        ///• Real-time processing monitoring
        ///• Comprehensive logging system
        ///• User-friendly interface with keyboard shortcuts
        ///
        ///© 2025 Trade Data Hub. All rights reserved.
        ///
        ///For support and updates, please visit our website or contact the development team.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts:
        ///
        ///File Operations:
        ///Ctrl+N - New
        ///Ctrl+O - Open
        ///Ctrl+S - Save
        ///Ctrl+Shift+S - Save As
        ///Alt+F4 - Exit
        ///
        ///Edit Operations:
        ///Ctrl+Z - Undo
        ///Ctrl+Y - Redo
        ///Ctrl+X - Cut
        ///Ctrl+C - Copy
        ///Ctrl+V - Paste
        ///Ctrl+A - Select All
        ///
        ///View Operations:
        ///F5 - Refresh
        ///F11 - Full Screen
        ///
        ///Help:
        ///F1 - User Manual.
        /// </summary>
        internal static string KeyboardShortcutsText {
            get {
                return ResourceManager.GetString("KeyboardShortcutsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start Guide:
        ///
        ///Import Process:
        ///1. Select 'Import' radio button
        ///2. Choose database view (typically 'ImportView')
        ///3. Select stored procedure
        ///4. Set date range (From Month to To Month)
        ///5. Click 'Generate Import Files'
        ///
        ///Export Process:
        ///1. Select 'Export' radio button
        ///2. Choose database view (typically 'ExportView')
        ///3. Select stored procedure
        ///4. Set date range (From Month to To Month)
        ///5. Click 'Generate Export Files'
        ///
        ///Tips:
        ///• Use F5 to refresh the interface
        ///• Monitor progress in the status panel
        ///• Check the Logs folder for detailed information
        ///• Generated files appear in IMPORT_Excel or EXPORT_Excel folders.
        /// </summary>
        internal static string QuickStartText {
            get {
                return ResourceManager.GetString("QuickStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Data Hub - User Manual
        ///
        ///Welcome to Trade Data Hub! This comprehensive tool helps you import and export trade data efficiently.
        ///
        ///Getting Started:
        ///1. Select your operation type (Import or Export)
        ///2. Choose your database view and stored procedure
        ///3. Set your date range using the month pickers
        ///4. Configure your parameters
        ///5. Click Generate to process your data
        ///
        ///Features:
        ///• Advanced filtering capabilities
        ///• Real-time progress monitoring
        ///• Automatic Excel file generation
        ///• Comprehensive logging system
        ///• Keyboard shortcuts for efficiency
        ///
        ///For detailed instructions on each feature, please refer to the individual help sections or contact support.
        /// </summary>
        internal static string UserManualText {
            get {
                return ResourceManager.GetString("UserManualText", resourceCulture);
            }
        }
    }
}
